### ISSUE TITLE
Wallust

### ISSUE THREAD

**Issue by zabihexes** [dlasagno/vscode-wal-theme#23]
Managed to get this working with [wallust](https://codeberg.org/explosion-mental/wallust). Leaving it here since it might be useful for someone.

`wallust.toml`
```toml
[[entry]]
# create ~/cache/wal folder first
template="pywal-colors"
target="~/.cache/wal/colors"
```

`pywal-colors` template
```
{color0}
{color1}
{color2}
{color3}
{color4}
{color5}
{color6}
{color7}
{color8}
{color9}
{color10}
{color11}
{color12}
{color13}
{color14}
{color15}
```
